const TOON_DATA = [
  { id: 'blot', name: 'Blot', ru: 'Блот', group: 'regular' },
  { id: 'boxten', name: 'Boxten', ru: 'Бокстен', group: 'regular' },
  { id: 'brightney', name: 'Brightney', ru: 'Брайтни', group: 'regular' },
  { id: 'brusha', name: 'Brusha', ru: 'Бруша', group: 'regular' },
  { id: 'connie', name: 'Connie', ru: 'Конни', group: 'regular' },
  { id: 'cosmo', name: 'Cosmo', ru: 'Космо', group: 'regular' },
  { id: 'finn', name: 'Finn', ru: 'Финн', group: 'regular' },
  { id: 'flutter', name: 'Flutter', ru: 'Флаттер', group: 'regular' },
  { id: 'gigi', name: 'Gigi', ru: 'Джиджи', group: 'regular' },
  { id: 'glisten', name: 'Glisten', ru: 'Глистен', group: 'regular' },
  { id: 'goob', name: 'Goob', ru: 'Губ', group: 'regular' },
  { id: 'looey', name: 'Looey', ru: 'Луи', group: 'regular' },
  { id: 'poppy', name: 'Poppy', ru: 'Поппи', group: 'regular' },
  { id: 'razzle-dazzle', name: 'Razzle & Dazzle', ru: 'Раззл и Даззл', group: 'regular' },
  { id: 'rodger', name: 'Rodger', ru: 'Роджер', group: 'regular' },
  { id: 'scraps', name: 'Scraps', ru: 'Скрапс', group: 'regular' },
  { id: 'shrimpo', name: 'Shrimpo', ru: 'Шримпо', group: 'regular' },
  { id: 'squirm', name: 'Squirm', ru: 'Сквирм', group: 'regular' },
  { id: 'teagan', name: 'Teagan', ru: 'Тиган', group: 'regular' },
  { id: 'tisha', name: 'Tisha', ru: 'Тиша', group: 'regular' },
  { id: 'toodles', name: 'Toodles', ru: 'Тудлс', group: 'regular' },
  { id: 'yatta', name: 'Yatta', ru: 'Ятта', group: 'regular' },

  { id: 'astro', name: 'Astro', ru: 'Астро', group: 'main' },
  { id: 'bassie', name: 'Bassie', ru: 'Басси', group: 'main-event' },
  { id: 'bobette', name: 'Bobette', ru: 'Бобетт', group: 'main-event' },
  { id: 'gourdy', name: 'Gourdy', ru: 'Горди', group: 'main-event' },
  { id: 'pebble', name: 'Pebble', ru: 'Пеббл', group: 'main' },
  { id: 'shelly', name: 'Shelly', ru: 'Шелли', group: 'main' },
  { id: 'sprout', name: 'Sprout', ru: 'Спраут', group: 'main' },
  { id: 'vee', name: 'Vee', ru: 'Ви', group: 'main' },

  { id: 'cocoa', name: 'Cocoa', ru: 'Кокоа', group: 'event' },
  { id: 'eggson', name: 'Eggson', ru: 'Эггсон', group: 'event' },
  { id: 'flyte', name: 'Flyte', ru: 'Флайт', group: 'event' },
  { id: 'eclipse', name: 'Eclipse', ru: 'Эклипс', group: 'event' },
  { id: 'ribecca', name: 'Ribecca', ru: 'Рибекка', group: 'event' },
  { id: 'soulvester', name: 'Soulvester', ru: 'Соулвестер', group: 'event' },
  { id: 'coal', name: 'Coal', ru: 'Коал', group: 'event' },
  { id: 'ginger', name: 'Ginger', ru: 'Джинджер', group: 'event' },
  { id: 'rudie', name: 'Rudie', ru: 'Руди', group: 'event' },
];

const TWISTED_DATA = [
  ...TOON_DATA.map(t => ({
    id: `twisted-${t.id}`,
    name: `Twisted ${t.name}`,
    ru: `Твистед ${t.ru}`,
    group: t.group.includes('event') ? 'event' : (t.group.includes('main') ? 'main' : 'regular')
  })),
  { id: 'twisted-dandy', name: 'Twisted Dandy', ru: 'Твистед Денди', group: 'lethal' },
  { id: 'twisted-dyle', name: 'Twisted Dyle', ru: 'Твистед Дайл', group: 'lethal' },
];

const ACHIEVEMENT_DATA = [
  ['speed-walker','Speed Walker','Бронза','Пройти 50 000 метров','distance',50000],
  ['long-distance-runner','Long Distance Runner','Серебро','Пройти 500 000 метров','distance',500000],
  ['marathon-runner','Marathon Runner','Золото','Пройти 5 000 000 метров','distance',5000000],
  ['machine-enthusiast','Machine Enthusiast','Бронза','Завершить 100 машин','machines',100],
  ['machine-master','Machine Master','Серебро','Завершить 1 000 машин','machines',1000],
  ['the-machine','THE Machine','Золото','Завершить 10 000 машин','machines',10000],
  ['item-finder','Item Finder','Бронза','Поднять 100 предметов','items',100],
  ['item-tracker','Item Tracker','Серебро','Поднять 1 000 предметов','items',1000],
  ['item-hunter','Item Hunter','Золото','Поднять 10 000 предметов','items',10000],
  ['hissy-fit','Hissy Fit','Радужное','Пройти этаж Дайла за Шримпо','custom',1],
  ['sightseer','Sightseer','Серебро','Посетить 15 уникальных этажей-карт за один забег','custom',15],
  ['clocked-in','Clocked In','Бронза','Пройти этаж Дайла','custom',1],
  ['overtime','Overtime','Радужное','Пройти этаж Дайла 25 раз','custom',25],
  ['gossip-bud','Gossip Bud','Бронза','Прослушать 25 уникальных сплетен Денди','custom',25],
  ['gossip-time','Gossip Time','Бронза','Прослушать 25 уникальных сплетен Дайла','custom',25],
  ['double-digits','Double Digits!','Бронза','Завершить 10-й этаж','floor',10],
  ['skilled-toon','Skilled Toon!','Серебро','Завершить 25-й этаж','floor',25],
  ['super-skilled-pro','Super Skilled Pro!','Золото','Завершить 50-й этаж','floor',50],
  ['twisteds-fear-me','Twisteds Fear Me','Радужное','Завершить 100-й этаж','floor',100],
  ['fine-dining','Fine Dining','Золото','Съесть 10 уникальных книжных полок на одном этаже за Сквирма','custom',10],
  ['stealth-mission','Stealth Mission','Серебро','Пройти этаж, ни разу не попавшись на глаза','custom',1],
  ['speed-runner','Speed Runner','Золото','Пройти этаж менее чем за 1 минуту','custom',1],
  ['center-of-attention','Center of Attention','Золото','Одновременно отвлечь 6 твистедов','custom',6],
  ['master-of-many','Master of Many','Золото','Завершить мастерство 20 тунов','masteries',20],
  ['what-a-deal','What a Deal!','Бронза','Купить все 3 предмета за один визит в магазин Денди','custom',1],
  ['geared-up','Geared Up','Серебро','Купить все 3 предмета в предзабеговом магазине','custom',1],
  ['main-character','Main Character','Радужное','Пройти этаж составом из 8 уникальных главных тунов','custom',1],
  ['get-to-where','Get To Where?','Бронза','Использовать стикер GTE во время паники','custom',1],
  ['attached','Attached','Бронза','Находиться рядом с Твистед Глистеном 30 секунд подряд','custom',30],
  ['helpful-hugger','Helpful Hugger','Серебро','Затащить игрока в лифт способностью Губа во время паники','custom',1],
  ['investigator','Investigator','Бронза','Собрать все капсулы исследования на одном этаже','custom',1],
  ['lights-out','Lights Out','Бронза','Пережить блэкаут, вызванный Твистед Брайтни','custom',1],
  ['center-stage','Center Stage','Серебро','Главным туном пройти этаж с Твистед Денди','custom',1],
  ['empty-handed','Empty Handed','Серебро','Пережить 5 этажей за забег без тринкетов','custom',5],
  ['squeaky-clean','Squeaky Clean','Серебро','Пройти этаж с утечкой ихора, не попав в лужу','custom',1],
  ['bedtime','Bedtime','Серебро','Дать стамину сразу 3 тунам способностью Астро','custom',1],
  ['winning-choice','Winning Choice','Золото','Выбрать карточку единогласно восьмью голосами','custom',1],
  ['quick-reaction-time','Quick Reaction Time','Золото','Сделать 10 идеальных скилл-чеков на одном этаже туном с 1 звездой','custom',10],
  ['unstoppably-healthy','Unstoppably Healthy','Серебро','Заполнить весь инвентарь лечащими предметами','custom',1],
  ['teamwork','Teamwork','Бронза','Одновременно с другим игроком закончить дуо-машину','custom',1],
  ['all-together','All Together','Золото','Закончить дуо-машину, в которую внесли вклад 8 тунов','custom',1],
  ['egg-hunter','Egg Hunter','Серебро','Найти все яйца в лобби','custom',10],
  ['sprout-fan','Sprout Fan','Оникс','Выполнить хотя бы одно недельное задание Спраута','custom',1],
  ['nurturer','Nurturer','Бронза','Помочь Bud пройти этаж 10 раз','custom',10],
  ['caretaker','Caretaker','Серебро','Помочь Bud пройти этаж 25 раз','custom',25],
  ['cultivator','Cultivator','Золото','Помочь Bud пройти этаж 50 раз','custom',50],
  ['green-thumb','Green Thumb','Радужное','Помочь Bud пройти этаж 100 раз','custom',100],
  ['finn-fan','Finn Fan','Оникс','Выполнить хотя бы одно недельное задание Финна','custom',1],
  ['swimmy-barnaby','Swimmy Barnaby','Серебро','Набрать 100 очков в Swimmy Barnaby','custom',100],
].map(([id,name,tier,description,kind,target]) => ({id,name,tier,description,kind,target}));

// Точные требования мастерства из таблицы Dandy's World Wiki.
// Формат: [идентификатор, название на русском, требуемое количество].
const MASTERY_TASKS = {
  astro: [
    ['active-ability','Использовать активную способность',100],
    ['dandy-purchases','Купить предметы в магазине Денди',25],
    ['distance','Пройти метров',150000],
    ['blackouts','Пережить блэкауты',12],
    ['items-picked','Поднять предметы',125],
    ['items-used','Использовать предметы',125],
  ],
  bassie: [
    ['active-ability','Использовать активную способность',120],
    ['floor-reached','Достичь этажа',20],
    ['distance','Пройти метров',160000],
    ['machines','Завершить машины',110],
    ['floors','Пережить этажи',65],
    ['items-used','Использовать предметы',130],
  ],
  blot: [
    ['active-ability','Использовать активную способность',40],
    ['research-capsules','Поднять капсулы исследования',100],
    ['floors','Пережить этажи',30],
    ['looey-yatta-floors','Пережить этажи с Луи и Яттой в забеге',10],
    ['distance','Пройти метров',120000],
    ['items-used','Использовать предметы',100],
  ],
  bobette: [
    ['active-ability','Использовать активную способность',100],
    ['floor-reached','Достичь этажа',20],
    ['distance','Пройти метров',150000],
    ['machines','Завершить машины',120],
    ['floors','Пережить этажи',60],
    ['items-used','Использовать предметы',125],
  ],
  boxten: [
    ['machines','Завершить машины',50],
    ['floors','Пережить этажи',25],
    ['distance','Пройти метров',50000],
    ['items-picked','Поднять предметы',30],
    ['party-7-floors','Пережить этажи с 7 другими игроками',1],
    ['items-used','Использовать предметы',30],
  ],
  brightney: [
    ['active-ability','Использовать активную способность',50],
    ['machines','Завершить машины',50],
    ['distance','Пройти метров',80000],
    ['blackouts','Пережить блэкауты',15],
    ['items-picked','Поднять предметы',60],
    ['items-used','Использовать предметы',60],
  ],
  brusha: [
    ['active-ability','Использовать активную способность',100],
    ['machines','Завершить машины',65],
    ['tisha-floors','Пережить этажи с Тишей в забеге',5],
    ['dandy-purchases','Купить предметы в магазине Денди',20],
    ['floors','Пережить этажи',25],
    ['distance','Пройти метров',40000],
  ],
  coal: [
    ['active-ability','Использовать активную способность',100],
    ['items-picked','Поднять предметы',120],
    ['distance','Пройти метров',90000],
    ['research-capsules','Поднять капсулы исследования',85],
    ['pebble-floors','Пережить этажи с Пебблом в забеге',5],
    ['items-used','Использовать предметы',85],
  ],
  cocoa: [
    ['machines','Завершить машины',65],
    ['yatta-floors','Пережить этажи с Яттой в забеге',20],
    ['items-used','Использовать предметы',120],
    ['items-picked','Поднять предметы',135],
    ['distance','Пройти метров',90000],
    ['bonbons-used','Использовать BonBon',35],
  ],
  connie: [
    ['active-ability','Использовать активную способность',100],
    ['floors','Пережить этажи',50],
    ['distance','Пройти метров',55000],
    ['machines','Завершить машины',50],
    ['party-2-floors','Пережить этажи с 2 другими игроками',5],
    ['items-used','Использовать предметы',50],
  ],
  cosmo: [
    ['active-ability','Использовать активную способность',25],
    ['floors','Пережить этажи',30],
    ['distance','Пройти метров',60000],
    ['items-picked','Поднять предметы',35],
    ['party-3-floors','Пережить этажи с 3 другими игроками',5],
    ['items-used','Использовать предметы',35],
  ],
  eclipse: [
    ['blackouts','Пережить блэкауты',15],
    ['floors','Пережить этажи',50],
    ['distance','Пройти метров',100000],
    ['twisted-encounters','Встретить твистедов',75],
    ['party-7-floors','Пережить этажи с 7 другими игроками',3],
    ['items-used','Использовать предметы',80],
  ],
  eggson: [
    ['machines','Завершить машины',30],
    ['research-capsules','Поднять капсулы исследования',30],
    ['floors','Пережить этажи',25],
    ['passive-ability','Активировать пассивную способность',80],
    ['items-picked','Поднять предметы',35],
    ['distance','Пройти метров',50000],
  ],
  finn: [
    ['dandy-purchases','Купить предметы в магазине Денди',5],
    ['items-picked','Поднять предметы',30],
    ['distance','Пройти метров',55000],
    ['machines','Завершить машины',45],
    ['floors','Пережить этажи',30],
    ['items-used','Использовать предметы',30],
  ],
  flutter: [
    ['active-ability','Использовать активную способность',100],
    ['floor-reached','Достичь этажа',12],
    ['distance','Пройти метров',90000],
    ['items-picked','Поднять предметы',60],
    ['floors','Пережить этажи',45],
    ['items-used','Использовать предметы',60],
  ],
  flyte: [
    ['active-ability','Использовать активную способность',85],
    ['floor-reached','Достичь этажа',12],
    ['flutter-floors','Пережить этажи с Флаттер в забеге',5],
    ['machines','Завершить машины',60],
    ['floors','Пережить этажи',45],
    ['distance','Пройти метров',90000],
  ],
  gigi: [
    ['active-ability','Использовать активную способность',50],
    ['machines','Завершить машины',65],
    ['distance','Пройти метров',85000],
    ['dandy-purchases','Купить предметы в магазине Денди',30],
    ['items-picked','Поднять предметы',150],
    ['items-used','Использовать предметы',200],
  ],
  ginger: [
    ['active-ability','Использовать активную способность',25],
    ['floors','Пережить этажи',30],
    ['distance','Пройти метров',55000],
    ['items-picked','Поднять предметы',35],
    ['party-2-floors','Пережить этажи с 2 другими игроками',10],
    ['items-used','Использовать предметы',35],
  ],
  glisten: [
    ['active-ability','Использовать активную способность',60],
    ['items-picked','Поднять предметы',60],
    ['distance','Пройти метров',100000],
    ['machines','Завершить машины',100],
    ['floors','Пережить этажи',50],
    ['items-used','Использовать предметы',60],
  ],
  goob: [
    ['active-ability','Использовать активную способность',100],
    ['party-4-floors','Пережить этажи с 4 другими игроками',3],
    ['distance','Пройти метров',100000],
    ['items-picked','Поднять предметы',80],
    ['scraps-floors','Пережить этажи со Скрапс в забеге',25],
    ['items-used','Использовать предметы',80],
  ],
  gourdy: [
    ['active-ability','Использовать активную способность',120],
    ['items-picked','Поднять предметы',100],
    ['main-floors','Пережить этажи с любым главным туном',30],
    ['machines','Завершить машины',175],
    ['floors','Пережить этажи',70],
    ['distance','Пройти метров',150000],
  ],
  looey: [
    ['machines','Завершить машины',30],
    ['research-capsules','Поднять капсулы исследования',50],
    ['floors','Пережить этажи',30],
    ['passive-ability','Активировать пассивную способность',30],
    ['items-picked','Поднять предметы',45],
    ['distance','Пройти метров',80000],
  ],
  pebble: [
    ['active-ability','Использовать активную способность',145],
    ['items-picked','Поднять предметы',200],
    ['floors','Пережить этажи',75],
    ['twisted-encounters','Встретить твистедов',80],
    ['floor-reached','Достичь этажа',20],
    ['distance','Пройти метров',175000],
  ],
  poppy: [
    ['machines','Завершить машины',30],
    ['items-picked','Поднять предметы',30],
    ['distance','Пройти метров',50000],
    ['passive-ability','Активировать пассивную способность',30],
    ['floors','Пережить этажи',25],
    ['items-used','Использовать предметы',30],
  ],
  'razzle-dazzle': [
    ['dandy-purchases','Купить предметы в магазине Денди',10],
    ['items-picked','Поднять предметы',100],
    ['distance','Пройти метров',100000],
    ['machines','Завершить машины',50],
    ['floors','Пережить этажи',75],
    ['items-used','Использовать предметы',100],
  ],
  ribecca: [
    ['dandy-purchases','Купить предметы в магазине Денди',25],
    ['ichor-spills','Пережить утечки ихора',5],
    ['distance','Пройти метров',50000],
    ['machines','Завершить машины',30],
    ['items-picked','Поднять предметы',35],
    ['items-used','Использовать предметы',35],
  ],
  rodger: [
    ['research-percent','Собрать процентов исследования твистедов',1000],
    ['research-capsules','Поднять капсулы исследования',125],
    ['distance','Пройти метров',75000],
    ['twisted-encounters','Встретить твистедов',100],
    ['items-picked','Поднять предметы',60],
    ['items-used','Использовать предметы',60],
  ],
  rudie: [
    ['active-ability','Использовать активную способность',60],
    ['items-picked','Поднять предметы',35],
    ['distance','Пройти метров',50000],
    ['machines','Завершить машины',30],
    ['floors','Пережить этажи',25],
    ['items-used','Использовать предметы',30],
  ],
  scraps: [
    ['active-ability','Использовать активную способность',100],
    ['twisted-encounters','Встретить твистедов',25],
    ['distance','Пройти метров',85000],
    ['dandy-purchases','Купить предметы в магазине Денди',12],
    ['items-picked','Поднять предметы',60],
    ['items-used','Использовать предметы',60],
  ],
  shelly: [
    ['active-ability','Использовать активную способность',125],
    ['items-picked','Поднять предметы',100],
    ['party-4-floors','Пережить этажи с 4 другими игроками',15],
    ['machines','Завершить машины',150],
    ['floors','Пережить этажи',80],
    ['distance','Пройти метров',150000],
  ],
  shrimpo: [
    ['machines','Завершить машины',30],
    ['floors','Пережить этажи',30],
    ['distance','Пройти метров',50000],
    ['items-picked','Поднять предметы',30],
    ['party-2-floors','Пережить этажи с 2 другими игроками',5],
    ['items-used','Использовать предметы',30],
  ],
  soulvester: [
    ['blackouts','Пережить блэкауты',5],
    ['floors','Пережить этажи',50],
    ['distance','Пройти метров',50000],
    ['machines','Завершить машины',100],
    ['connie-floors','Пережить этажи с Конни в забеге',10],
    ['items-used','Использовать предметы',50],
  ],
  sprout: [
    ['active-ability','Использовать активную способность',50],
    ['floors','Пережить этажи',75],
    ['cosmo-floors','Пережить этажи с Космо в забеге',30],
    ['items-picked','Поднять предметы',85],
    ['party-4-floors','Пережить этажи с 4 другими игроками',15],
    ['distance','Пройти метров',150000],
  ],
  squirm: [
    ['active-ability','Использовать активную способность',100],
    ['machines','Завершить машины',100],
    ['bookshelves-eaten','Съесть книжные полки',100],
    ['floors','Пережить этажи',30],
    ['brightney-floors','Пережить этажи с Брайтни в забеге',5],
    ['distance','Пройти метров',60000],
  ],
  teagan: [
    ['active-ability','Использовать активную способность',25],
    ['twisted-encounters','Встретить твистедов',25],
    ['distance','Пройти метров',75000],
    ['dandy-purchases','Купить предметы в магазине Денди',15],
    ['items-picked','Поднять предметы',60],
    ['items-used','Использовать предметы',60],
  ],
  tisha: [
    ['active-ability','Использовать активную способность',30],
    ['items-picked','Поднять предметы',30],
    ['party-3-floors','Пережить этажи с 3 другими игроками',5],
    ['machines','Завершить машины',30],
    ['floors','Пережить этажи',25],
    ['distance','Пройти метров',50000],
  ],
  toodles: [
    ['active-ability','Использовать активную способность',75],
    ['items-picked','Поднять предметы',35],
    ['distance','Пройти метров',52500],
    ['machines','Завершить машины',30],
    ['floors','Пережить этажи',30],
    ['items-used','Использовать предметы',35],
  ],
  vee: [
    ['active-ability','Использовать активную способность',150],
    ['machines','Завершить машины',150],
    ['items-picked','Поднять предметы',100],
    ['blackouts','Пережить блэкауты',12],
    ['twisted-encounters','Встретить твистедов',75],
    ['distance','Пройти метров',150000],
  ],
  yatta: [
    ['machines','Завершить машины',85],
    ['items-picked','Поднять предметы',120],
    ['distance','Пройти метров',45000],
    ['research-capsules','Поднять капсулы исследования',50],
    ['looey-floors','Пережить этажи с Луи в забеге',20],
    ['items-used','Использовать предметы',120],
  ],
};

function getMasteryTasks(toonId) {
  const tasks = MASTERY_TASKS[toonId] || [];
  return tasks.map(([id, label, target]) => ({ id, label, current: 0, target }));
}
