-- Dandy's Progress v11 — друзья и личные сообщения
-- Supabase → SQL Editor → New query → вставь весь файл → Run.
-- Файл идемпотентный: его можно запускать повторно.

-- 1. Дружба и заявки.
create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references auth.users(id) on delete cascade,
  addressee_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (requester_id <> addressee_id)
);

create unique index if not exists friendships_unique_pair_idx
  on public.friendships (
    least(requester_id::text, addressee_id::text),
    greatest(requester_id::text, addressee_id::text)
  );
create index if not exists friendships_requester_idx on public.friendships (requester_id, status);
create index if not exists friendships_addressee_idx on public.friendships (addressee_id, status);

create or replace function public.protect_friendship_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.requester_id <> old.requester_id or new.addressee_id <> old.addressee_id then
    raise exception 'Friendship participants cannot be changed';
  end if;
  return new;
end;
$$;

drop trigger if exists protect_friendship_update_trigger on public.friendships;
create trigger protect_friendship_update_trigger
before update on public.friendships
for each row execute function public.protect_friendship_update();

-- 2. Блокировки.
create table if not exists public.user_blocks (
  blocker_id uuid not null references auth.users(id) on delete cascade,
  blocked_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);

-- Служебные проверки выполняются с правами владельца функции,
-- чтобы RLS не вызывал рекурсивные проверки.
create or replace function public.are_friends(user_a uuid, user_b uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select user_a is not null and user_b is not null and exists (
    select 1 from public.friendships f
    where f.status = 'accepted'
      and ((f.requester_id = user_a and f.addressee_id = user_b)
        or (f.requester_id = user_b and f.addressee_id = user_a))
  );
$$;

create or replace function public.is_blocked_pair(user_a uuid, user_b uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select user_a is not null and user_b is not null and exists (
    select 1 from public.user_blocks b
    where (b.blocker_id = user_a and b.blocked_id = user_b)
       or (b.blocker_id = user_b and b.blocked_id = user_a)
  );
$$;

create or replace function public.can_message(user_a uuid, user_b uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.are_friends(user_a, user_b)
     and not public.is_blocked_pair(user_a, user_b);
$$;

-- 3. Личные сообщения.
create table if not exists public.direct_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references auth.users(id) on delete cascade,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  read_at timestamptz,
  check (sender_id <> recipient_id),
  check (char_length(btrim(body)) between 1 and 500)
);
create index if not exists direct_messages_pair_time_idx on public.direct_messages (sender_id, recipient_id, created_at);
create index if not exists direct_messages_unread_idx on public.direct_messages (recipient_id, sender_id, created_at) where read_at is null;

-- Запрещает редактировать текст и участников уже отправленного сообщения.
create or replace function public.protect_direct_message_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.sender_id <> old.sender_id
     or new.recipient_id <> old.recipient_id
     or new.body <> old.body
     or new.created_at <> old.created_at then
    raise exception 'Only read_at can be updated';
  end if;
  return new;
end;
$$;

drop trigger if exists protect_direct_message_update_trigger on public.direct_messages;
create trigger protect_direct_message_update_trigger
before update on public.direct_messages
for each row execute function public.protect_direct_message_update();

-- 4. RLS: участники видят только собственные связи и переписки.
alter table public.friendships enable row level security;
alter table public.user_blocks enable row level security;
alter table public.direct_messages enable row level security;

drop policy if exists "Friendships visible to participants" on public.friendships;
create policy "Friendships visible to participants"
on public.friendships for select to authenticated
using (auth.uid() = requester_id or auth.uid() = addressee_id);

drop policy if exists "Users can send friend requests" on public.friendships;
create policy "Users can send friend requests"
on public.friendships for insert to authenticated
with check (
  auth.uid() = requester_id
  and requester_id <> addressee_id
  and status = 'pending'
  and not public.is_blocked_pair(requester_id, addressee_id)
);

drop policy if exists "Recipients can accept requests" on public.friendships;
create policy "Recipients can accept requests"
on public.friendships for update to authenticated
using (auth.uid() = addressee_id and status = 'pending')
with check (auth.uid() = addressee_id and status = 'accepted');

drop policy if exists "Participants can remove friendships" on public.friendships;
create policy "Participants can remove friendships"
on public.friendships for delete to authenticated
using (auth.uid() = requester_id or auth.uid() = addressee_id);

drop policy if exists "Users can read own blocks" on public.user_blocks;
create policy "Users can read own blocks"
on public.user_blocks for select to authenticated
using (auth.uid() = blocker_id);

drop policy if exists "Users can block others" on public.user_blocks;
create policy "Users can block others"
on public.user_blocks for insert to authenticated
with check (auth.uid() = blocker_id and blocker_id <> blocked_id);

drop policy if exists "Users can update own blocks" on public.user_blocks;
create policy "Users can update own blocks"
on public.user_blocks for update to authenticated
using (auth.uid() = blocker_id)
with check (auth.uid() = blocker_id);

drop policy if exists "Users can unblock others" on public.user_blocks;
create policy "Users can unblock others"
on public.user_blocks for delete to authenticated
using (auth.uid() = blocker_id);

drop policy if exists "Messages visible to participants" on public.direct_messages;
create policy "Messages visible to participants"
on public.direct_messages for select to authenticated
using (auth.uid() = sender_id or auth.uid() = recipient_id);

drop policy if exists "Friends can send messages" on public.direct_messages;
create policy "Friends can send messages"
on public.direct_messages for insert to authenticated
with check (
  auth.uid() = sender_id
  and public.can_message(sender_id, recipient_id)
);

drop policy if exists "Recipients can mark messages read" on public.direct_messages;
create policy "Recipients can mark messages read"
on public.direct_messages for update to authenticated
using (auth.uid() = recipient_id)
with check (auth.uid() = recipient_id);

drop policy if exists "Senders can delete own messages" on public.direct_messages;
create policy "Senders can delete own messages"
on public.direct_messages for delete to authenticated
using (auth.uid() = sender_id);

-- Друзья могут видеть профиль друг друга даже при выключенной публичности.
drop policy if exists "Public profiles are readable" on public.public_profiles;
create policy "Public profiles are readable"
on public.public_profiles for select
using (
  is_public = true
  or auth.uid() = user_id
  or public.are_friends(auth.uid(), user_id)
);

-- Явные права для API-ролей Supabase.
grant select, insert, update, delete on public.friendships to authenticated;
grant select, insert, delete on public.user_blocks to authenticated;
grant select, insert, update, delete on public.direct_messages to authenticated;
grant usage, select on sequence public.friendships_id_seq to authenticated;
grant usage, select on sequence public.direct_messages_id_seq to authenticated;
revoke execute on function public.are_friends(uuid, uuid) from public;
revoke execute on function public.is_blocked_pair(uuid, uuid) from public;
revoke execute on function public.can_message(uuid, uuid) from public;
grant execute on function public.are_friends(uuid, uuid) to anon, authenticated;
grant execute on function public.is_blocked_pair(uuid, uuid) to authenticated;
grant execute on function public.can_message(uuid, uuid) to authenticated;

-- 5. Realtime для мгновенных заявок и сообщений.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'friendships'
  ) then
    alter publication supabase_realtime add table public.friendships;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'direct_messages'
  ) then
    alter publication supabase_realtime add table public.direct_messages;
  end if;
end $$;
