-- Dandy's Progress v12 — административные бейджи профилей
-- Сначала должна быть установлена v11 (друзья и сообщения).
-- Supabase → SQL Editor → New query → вставь весь файл → Run.
-- Файл можно запускать повторно.

-- 1. Список администраторов. Клиент сайта не может сам назначать администраторов.
create table if not exists public.site_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.site_admins enable row level security;

drop policy if exists "Users can read own admin flag" on public.site_admins;
create policy "Users can read own admin flag"
on public.site_admins for select to authenticated
using (auth.uid() = user_id);

grant select on public.site_admins to authenticated;

create or replace function public.is_site_admin(check_user uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select check_user is not null and exists (
    select 1 from public.site_admins a where a.user_id = check_user
  );
$$;

revoke execute on function public.is_site_admin(uuid) from public;
grant execute on function public.is_site_admin(uuid) to authenticated;

-- 2. Бейджи. У каждого значка собственное имя, эмодзи, цвет и описание.
create table if not exists public.profile_badges (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(btrim(name)) between 1 and 32),
  icon text not null default '★' check (char_length(btrim(icon)) between 1 and 8),
  color text not null default 'gold' check (color in ('gold','green','blue','purple','pink','red','ink')),
  description text not null default '' check (char_length(description) <= 160),
  awarded_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now()
);

create index if not exists profile_badges_user_idx on public.profile_badges (user_id, created_at desc);

-- Администратору разрешено видеть даже закрытые профили в панели выдачи.
drop policy if exists "Public profiles are readable" on public.public_profiles;
create policy "Public profiles are readable"
on public.public_profiles for select
using (
  is_public = true
  or auth.uid() = user_id
  or public.are_friends(auth.uid(), user_id)
  or public.is_site_admin(auth.uid())
);

create or replace function public.can_view_profile_badges(target_user uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.public_profiles p
    where p.user_id = target_user
      and (
        p.is_public = true
        or auth.uid() = p.user_id
        or public.are_friends(auth.uid(), p.user_id)
        or public.is_site_admin(auth.uid())
      )
  );
$$;

revoke execute on function public.can_view_profile_badges(uuid) from public;
grant execute on function public.can_view_profile_badges(uuid) to anon, authenticated;

alter table public.profile_badges enable row level security;

drop policy if exists "Visible profile badges are readable" on public.profile_badges;
create policy "Visible profile badges are readable"
on public.profile_badges for select to anon, authenticated
using (public.can_view_profile_badges(user_id));

drop policy if exists "Admins can award badges" on public.profile_badges;
create policy "Admins can award badges"
on public.profile_badges for insert to authenticated
with check (
  public.is_site_admin(auth.uid())
  and awarded_by = auth.uid()
);

drop policy if exists "Admins can edit badges" on public.profile_badges;
create policy "Admins can edit badges"
on public.profile_badges for update to authenticated
using (public.is_site_admin(auth.uid()))
with check (public.is_site_admin(auth.uid()));

drop policy if exists "Admins can remove badges" on public.profile_badges;
create policy "Admins can remove badges"
on public.profile_badges for delete to authenticated
using (public.is_site_admin(auth.uid()));

grant select on public.profile_badges to anon, authenticated;
grant insert, update, delete on public.profile_badges to authenticated;
grant usage, select on sequence public.profile_badges_id_seq to authenticated;

-- 3. Realtime: после выдачи бейдж появляется без перезагрузки.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'profile_badges'
  ) then
    alter publication supabase_realtime add table public.profile_badges;
  end if;
end $$;

-- 4. ПОСЛЕ запуска файла назначь себя администратором отдельным запросом.
-- В Supabase: Authentication → Users → скопируй свой User UID.
-- Затем замени UUID ниже и запусти только эту строку БЕЗ двух дефисов в начале:
-- insert into public.site_admins (user_id) values ('ТВОЙ-USER-UID') on conflict (user_id) do nothing;
